name: flatnotes
services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:v5.2.2
    environment:
      - PUID=1000
      - PGID=1000
      - FLATNOTES_AUTH_TYPE=none
    volumes:
      - /DATA/AppData/flatnotes:/data
    ports:
      - ${WEBUI_PORT:-8080}:8080
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: flatnotes
  author: Wallace
  category: Outros
  description:
    pt_BR: Um aplicativo simples de blocos de notas.
    en_US: A simple notepad application.
  developer: dullage
  icon: https://cdn.kubesail.com/prod/templates/jphj/flatnotes/88ad2612a951.jpg
  tagline:
    pt_BR: Um aplicativo simples e rápido para anotações. 
    en_US: A simple and fast note-taking app. 
  thumbnail: https://exemplo.com/flatnotes/thumbnail.png 
  title:
    pt_BR: Flatnotes
    en_US: Flatnotes
  tips:
    before_install:
      pt_BR: |
        # Dicas de instalação em português [6]
        Lembre-se de alterar a senha padrão após a instalação.
  index: / 
  port_map: ${WEBUI_PORT:-8080}