name: paperless-ngx
services:
  paperless-ngx:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Sao_Paulo
    image: linuxserver/paperless-ngx:1.8.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8000"
          description:
            en_us: ""

      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /data
          description:
            en_us: ""
    container_name: paperless-ngx
x-casaos:
  architectures:
    - amd64
    - arm64
  main: paperless-ngx
  author: Wallace
  category: Backup
  description:
    en_us: paperless-ngx is a free, open source, backup client that securely stores encrypted, incremental, compressed backups on cloud storage services and remote file servers.
    pt_br: O paperless-ngx é um cliente de backup gratuito e de código aberto que armazena de forma segura backups criptografados, incrementais e compactados em serviços de armazenamento em nuvem e servidores de arquivos remotos.
  developer: paperless-ngx
  icon: https://icon.casaos.io/main/all/paperless.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/paperless-ngx/thumbnail.png
  tips: {}
  title:
    en_us: paperless-ngx
    pt_br: paperless-ngx
  index: /
  port_map: "8000"
