name: paperless-ngx
services:
  broker:
    container_name: broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/data:/data
    x-casaos:
      volumes:
        - container: /config
          description:
            en_us: ""
  webserver:
    container_name: webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - /DATA/AppData/$AppID/data:/usr/src/paperless/data
      - /DATA/AppData/$AppID/media:/usr/src/paperless/media
      - /DATA/AppData/$AppID/export:/usr/src/paperless/export
      - /DATA/AppData/$AppID/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
    x-casaos:
      envs:
        - container: PAPERLESS_REDIS
          description:
            en_us: ""
      volumes:
        - container: /usr/src/paperless/data
          description:
            en_us: ""
        - container: /usr/src/paperless/media
          description:
            en_us: ""
        - container: /usr/src/paperless/export
          description:
            en_us: ""
        - container: /usr/src/paperless/consume
          description:
            en_us: ""

x-casaos:
  architectures:
    - amd64
    - arm64
  main: webserver
  author: Wallace
  category: backup
  description:
    en_us: Duplicati is a free, open source, backup client that securely stores encrypted, incremental, compressed backups on cloud storage services and remote file servers.
  developer: duplicati
  icon: https://icon.casaos.io/main/all/duplicati.png
  title:
    en_us: Papertest
  index: /
  port_map: "8000"
