name: paperless-ngx
services:
  broker:
    container_name: broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /DATA/AppData/paperless:/data

  webserver:
    container_name: webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:2.11.0
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - /DATA/AppData/paperless/data:/usr/src/paperless/data
      - /DATA/AppData/paperless/media:/usr/src/paperless/media
      - /DATA/AppData/paperless/export:/usr/src/paperless/export
      - /DATA/AppData/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_ADMIN_USER: casaos
      PAPERLESS_ADMIN_PASSWORD: casaos
x-casaos:
  architectures:
    - amd64
    - arm64
    - armhf
  main: webserver
  author: Wallace
  category: Backup
  developer: Daniel Quinn
  description:
    en_us: Paperless-ngx⁠ is an application by Daniel Quinn and contributors that indexes your scanned documents and allows you to easily search for documents and store metadata alongside your documents.
    pt_br: Paperless-ngx é um aplicativo desenvolvido por Daniel Quinn e colaboradores que indexa documentos digitalizados, facilitando a busca e o armazenamento de metadados junto aos documentos.
  tagline:
    en_us: Indexes scanned documents for easy search and metadata storage
    pt_br: Indexa documentos digitalizados para busca e armazenamento de metadados
  icon: https://icon.casaos.io/main/all/paperless.png
  title:
    en_us: paperless
  index: /
  port_map: "8000"