name: paperless-ngx
services:
  broker:
    container_name: broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /DATA/AppData/paperless:/data
    x-casaos:
      - container: /data
        description:
          en_us: ""

  webserver:
    container_name: webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - /DATA/AppData/paperless/data:/usr/src/paperless/data
      - /DATA/AppData/paperless/media:/usr/src/paperless/media
      - /DATA/AppData/paperless/export:/usr/src/paperless/export
      - /DATA/AppData/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    x-casaos:
      envs:
        - container: PAPERLESS_REDIS
          description:
            en_us: ""
        - container: PAPERLESS_TIKA_ENABLED
          description:
            en_us: ""
        - container: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
          description:
            en_us: ""
        - container: PAPERLESS_TIKA_ENDPOINT
          description:
            en_us: ""
      ports:
        - container: "8000"
          description:
            en_us: ""
      volumes:
        - container: /usr/src/paperless/data
          description:
            en_us: ""
        - container: /usr/src/paperless/media
          description:
            en_us: ""
        - container: /usr/src/paperless/export
          description:
            en_us: ""
        - container: /usr/src/paperless/consume
          description:
            en_us: ""

  gotenberg:
    container_name: gotenberg
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    container_name: tika
    image: docker.io/apache/tika:latest
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm64
  main: webserver
  author: Wallace
  category: WCasaOS
  developer: Matiss Janis Aboltins
  project_url: https://actualbudget.org/
  description:
    en_us: Actual Budget is a super fast and privacy-focused app for managing your finances. At its heart is the well proven and much loved Envelope Budgeting methodology. You own your data and can do whatever you want with it. Featuring multi-device sync, optional end-to-end encryption and so much more.
    pt_br: Actual Budget é um aplicativo super rápido e focado na privacidade para gerenciar suas finanças. Em sua essência está a comprovada e muito apreciada metodologia de Orçamento de Envelope. Você possui seus dados e pode fazer o que quiser com eles. Apresentando sincronização de vários dispositivos, criptografia ponta a ponta opcional e muito mais.
  tagline:
    en_us: Local-first OpenSource Budget tool
    pt_br: Ferramenta de orçamento OpenSource local
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/actual.png
  screenshot_link:
    - https://actualbudget.org/img/homepage/actual-main-budget.png
    - https://actualbudget.org/img/homepage/actual-main-transaction.png
    - https://actualbudget.org/img/homepage/actual-report-cash-flow.png
  title:
    en_us: Paperteste
  index: /
  port_map: "8000"