name: paperless-ngx
services:
  broker:
    container_name: broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /DATA/AppData/paperless:/data
  webserver:
    container_name: webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:2.11.0
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
    volumes:
      - /DATA/AppData/paperless/data:/usr/src/paperless/data
      - /DATA/AppData/paperless/media:/usr/src/paperless/media
      - /DATA/AppData/paperless/export:/usr/src/paperless/export
      - /DATA/AppData/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_TIME_ZONE: America/Sao_Paulo
      PAPERLESS_OCR_LANGUAGE: por
      PAPERLESS_ADMIN_USER: casaos
      PAPERLESS_ADMIN_PASSWORD: casaos
x-casaos:
  architectures:
    - amd64
    - arm64
    - armhf
  main: webserver
  author: Wallace
  category: Arquivo
  description:
    en_us: Actual Budget is a super fast and privacy-focused app for managing your finances. At its heart is the well proven and much loved Envelope Budgeting methodology. You own your data and can do whatever you want with it. Featuring multi-device sync, optional end-to-end encryption and so much more.
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/actual.png
  title:
    en_us: paperless
  index: /
  port_map: "8000"