name: baikal
services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    ports:
      - "8085:80"
    labels:
      tsdproxy.enable: true
      tsdproxy.name: baikal
    restart: unless-stopped
    volumes:
      - /DATA/AppData/baikal/config:/var/www/baikal/config
      - /DATA/AppData/baikal/data:/var/www/baikal/Specific
    networks:
      - baikal
networks:
  baikal:
    name: baikal
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm32
    - i386
  category: WCasaOS
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/baikal.png
  index: /
  port_map: "8085"
  title:
    custom: Baikal