name: baikal
services:
  baikal:
    container_name: baikal
    image: docker.io/ckulka/baikal:nginx
    ports:
      - "8089:80"
    labels:
      tsdproxy.enable: true
      tsdproxy.name: baikal
    restart: unless-stopped
    volumes:
      - /DATA/AppData/baikal/config:/var/www/baikal/config
      - /DATA/AppData/baikal/Specific:/var/www/baikal/Specific

x-casaos:
  architectures:
    - amd64
  category: WCasaOS
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/baikal.png
  title:
    custom: Baikal