name: immich

services:
  immich-server:
    container_name: immich-server
    image: altran1502/immich-server:release
    command: ["start.sh", "immich"]
    ports:
      - 2283:3001
    volumes:
      - /DATA/AppData/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=casaos
      - DB_USERNAME=casaos
      - TZ=America/Sao_Paulo
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - immich
    privileged: false

  immich-machine-learning:
    container_name: immich-machine-learning
    image: altran1502/immich-machine-learning:release
    volumes:
      - /DATA/AppData/immich/model-cache:/cache
    environment:
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=casaos
      - DB_USERNAME=casaos
    restart: unless-stopped
    networks:
      - immich
    privileged: false

  redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - /DATA/AppData/immich/redis:/data
    restart: unless-stopped
    networks:
      - immich

  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /DATA/AppData/immich/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped
    networks:
      - immich

networks:
  immich:
    name: immich

x-casaos:
  architectures:
    - amd64
    - arm64
  main: immich-server
  description:
    en_us: Self-hosted photo and video storage.
  tagline:
    en_us: Immich
  developer: ""
  author: Wallace
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
  thumbnail: ""
  title:
    en_us: Immich
  category: Fotos
  port_map: "2283"