name: immich
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.112.1
    command: ["start.sh", "immich"]
    ports:
      - 2283:3001
    volumes:
      - /DATA/AppData/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: immich
      DB_PORT: "5432"
      TZ: America/Sao_Paulo
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on:
      - redis
      - database
    restart: always
  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:v1.112.1
    command: ["start.sh", "microservices"]
    volumes:
      - /DATA/AppData/immich/upload:/usr/src/app/upload
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      TZ: America/Sao_Paulo
      REDIS_HOSTNAME: immich-redis
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.112.1
    volumes:
      - /DATA/AppData/immich/model-cache:/cache
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: casaos
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: always
  redis:
    container_name: immich-redis
    image: redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    restart: always
  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /DATA/AppData/immich/pgdata:/var/lib/postgresql/data
    restart: always
x-casaos:
  architectures:
    - amd64
    - arm64
  main: immich-server
  description:
    en_us: Self-hosted photo and video storage.
  tagline:
    en_us: Immich
  developer: ""
  author: Wallace
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
  thumbnail: ""
  title:
    en_us: Immich
  category: Fotos
  port_map: "2283"