name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.108.0
    environment:
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich-postgres
    volumes:
      - /DATA/AppData/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.108.0
    volumes:
      - /DATA/AppData/immich/model-cache:/cache
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /DATA/AppData/immich/pgdata:/var/lib/postgresql/data
    restart: always
x-casaos:
  architectures:
    - amd64
    - arm64
  main: immich-server
  description:
    en_us: Self-hosted photo and video storage.
  tagline:
    en_us: Immich
  developer: ""
  author: Wallace
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
  thumbnail: ""
  title:
    en_us: Immich
  category: Fotos
  port_map: "2283"