name: duplicati
services:
  duplicati:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Sao_Paulo
    image: linuxserver/duplicati:2.0.8
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8200
        published: "8200"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/backups
        target: /backups
      - type: bind
        source: /DATA
        target: /source
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ""
        - container: PGID
          description:
            en_us: ""
        - container: TZ
          description:
            en_us: ""
      ports:
        - container: "8200"
          description:
            en_us: ""

      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /backups
          description:
            en_us: ""
        - container: /source
          description:
            en_us: ""
    container_name: duplicati
x-casaos:
  architectures:
    - amd64
    - arm64
  main: duplicati
  author: Wallace
  category: Backup
  description:
    en_us: Duplicati is a free, open source, backup client that securely stores encrypted, incremental, compressed backups on cloud storage services and remote file servers.
    pt_br: O Duplicati é um cliente de backup gratuito e de código aberto que armazena de forma segura backups criptografados, incrementais e compactados em serviços de armazenamento em nuvem e servidores de arquivos remotos.
  developer: duplicati
  icon: https://icon.casaos.io/main/all/duplicati.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Duplicati/thumbnail.png
  tips: {}
  title:
    en_us: Duplicati
    pt_br: Duplicati
  index: /
  port_map: "8200"
