name: duplicati
services:
  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati:2.0.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /DATA/AppData/duplicati/config:/config
      - /DATA/AppData/duplicati/backups:/backups
      - /DATA:/source
    ports:
      - 8200:8200
    restart: unless-stopped
x-casaos:
  architectures:
    - amd64
    - arm64
  main: duplicati
  author: Wallace
  category: Backup
  developer: Daniel Quinn
  description:
    en_us: Duplicati⁠ works with standard protocols like FTP, SSH, WebDAV as well as popular services like Microsoft OneDrive, Amazon Cloud Drive & S3, Google Drive, box.com, Mega, hubiC and many others.
    pt_br: Duplicati trabalha com protocolos padrão como FTP, SSH, WebDAV, além de serviços populares como Microsoft OneDrive, Amazon Cloud Drive & S3, Google Drive, box.com, Mega, hubiC e muitos outros.
  tagline:
    en_us: Sistema para backup que funciona com vários serviços na nuvem.
    pt_br: System for backup that works with various cloud services.
  icon: https://icon.casaos.io/main/all/duplicati.png
  title:
    en_us: Duplicati
  index: /
  port_map: "8200"