name: siyuan
services:
  siyuan:
    container_name: siyuan
    image: b3log/siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=casaos']
    user: '1000:1000'
    ports:
      - 6806:6806
    volumes:
      - /DATA/AppData/siyuan/:/siyuan/workspace
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
x-casaos:
  architectures:
    - amd64
    - arm64
  main: siyuan
  author: Wallace
  category: WCasaOS
  developer: ""
  project_url: ""
  description:
    en_us: Actual Budget is a super fast and privacy-focused app for managing your finances. At its heart is the well proven and much loved Envelope Budgeting methodology. You own your data and can do whatever you want with it. Featuring multi-device sync, optional end-to-end encryption and so much more.
    pt_br: Actual Budget é um aplicativo super rápido e focado na privacidade para gerenciar suas finanças. Em sua essência está a comprovada e muito apreciada metodologia de Orçamento de Envelope. Você possui seus dados e pode fazer o que quiser com eles. Apresentando sincronização de vários dispositivos, criptografia ponta a ponta opcional e muito mais.
  tagline:
    en_us: Local-first OpenSource Budget tool
    pt_br: Ferramenta de orçamento OpenSource local
  icon: ""
  title:
    en_us: Siyuan
  index: /
  port_map: "6806"