name: actual-server
services:
  actual-server:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: actualbudget/actual-server:24.2.0
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: "256M"
    network_mode: bridge
    ports:
      - "5006:5006"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run Syncthing as specified uid.
        - container: PGID
          description:
            en_us: Run Syncthing as specified gid.
      ports:
        - container: "5006"
          description:
            en_us: WebUI HTTP Port

      volumes:
        - container: /data
          description:
            en_us: "Container Path: /data"
    container_name: actual-server
x-casaos:
  architectures:
    - amd64
    - arm64
  main: actual-server
  author: Wallace
  category: WCasaOS
  developer: Matiss Janis Aboltins
  project_url: https://actualbudget.org/
  description:
    en_us: Actual Budget is a super fast and privacy-focused app for managing your finances. At its heart is the well proven and much loved Envelope Budgeting methodology. You own your data and can do whatever you want with it. Featuring multi-device sync, optional end-to-end encryption and so much more.
    pt_br: Actual Budget é um aplicativo super rápido e focado na privacidade para gerenciar suas finanças. Em sua essência está a comprovada e muito apreciada metodologia de Orçamento de Envelope. Você possui seus dados e pode fazer o que quiser com eles. Apresentando sincronização de vários dispositivos, criptografia ponta a ponta opcional e muito mais.
  tagline:
    en_us: Local-first OpenSource Budget tool
    pt_br: Ferramenta de orçamento OpenSource local
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/actual.png
  screenshot_link:
    - https://actualbudget.org/img/homepage/actual-main-budget.png
    - https://actualbudget.org/img/homepage/actual-main-transaction.png
    - https://actualbudget.org/img/homepage/actual-report-cash-flow.png
  tips: {}
  title:
    en_us: Actual Budget
    pt_br: Actual Budget
  index: /
  port_map: "5006"