name: open-webui
services: 
  ollama:
    container_name: ollama
    image: ollama/ollama:0.3.6
    tty: true
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/open-webui/ollama:/root/.ollama
  
  openwebui:
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL= '/ollama'
    image: ghcr.io/open-webui/open-webui:v0.3.13
    labels:
      icon: https://avatars.githubusercontent.com/u/158137808?s=280&v=4
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /DATA/AppData/open-webui:/app/backend/data

x-casaos:
  architectures:
    - amd64
    - arm64
  main: open-webui
  author: Wallace
  category: WCasaOS
  description:
    en_us: "Open source web interface for local AI services"
  tagline:
    en_us: "OpenWebUI"
  developer: "OpenWebUI"
  icon: "https://avatars.githubusercontent.com/u/158137808?s=280&v=4"
  thumbnail: "https://github.com/open-webui/open-webui/raw/main/demo.gif"
  title:
    en_us: "OpenWebUI"
  port_map: "8080"
