name: open-webui
services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:ollama
    ipc: host
    ports:
      - "30000:8080"
    network_mode: bridge
    restart: always
    volumes:
      - /DATA/AppData/open-webui/data:/app/backend/data
      - /DATA/AppData/open-webui/ollama:/root/.ollama

x-casaos:
  architectures:
    - amd64
    - arm64
  main: open-webui
  developer: Tim J. Baek
  author: Wallace
  category: WCasaOS
  icon: https://raw.githubusercontent.com/wallacepnts/WCasaOS/main/Apps/open-webui/icon.png
  index: /
  port_map: "30000"
  title:
    custom: Open WebUI