version: '3'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:ollama
    ipc: host
    ports:
      - "30000:8080"
    network_mode: bridge
    restart: always
    volumes:
      - /DATA/AppData/open-webui/data:/app/backend/data
      - /DATA/AppData/ollama:/root/.ollama
x-casaos:
  architectures:
    - amd64
    - arm64
  author: Wallace
  category: WCasaOS
  icon: https://avatars.githubusercontent.com/u/158137808?s=280&v=4
  index: /
  port_map: "30000"
  title:
    custom: Open WebUI